version: "3.7"

services:
  app:
    image: node:14
    command: "npm run dev"
    ports:
      - '3000:3000'
    working_dir: /app
    volumes:
      - ./:/app

  postgres:
    image: postgres:13.4
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - rooftop-postgres-data:/var/lib/postgres/data/

volumes:
  rooftop-postgres-data:



